apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: ${VICTORIAMETRICS_URL}
    isDefault: true

    jsonData:
      timeInterval: 15s
